/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gestion_ingresos_radio_kat.UI;

import gestion_ingresos_radio_kat.UI.Propietarios.Comisiones.Logica.Modelo.AccesoDatos.Controladores_Vista_Logica.CrearCuentaControlador;
import gestion_ingresos_radio_kat.UI.Propietarios.Comisiones.Logica.Modelo.AccesoDatos.Controladores_Vista_Logica.LoginControlador;
import gestion_ingresos_radio_kat.UI.RegistroUnidadGUI;

import javax.swing.JOptionPane;

public class CrearCuentaGUI extends javax.swing.JFrame {

    CrearCuentaControlador ca;

    public CrearCuentaGUI() {
        initComponents();
        ca = new CrearCuentaControlador("");
        ca = new CrearCuentaControlador("usuariosinvitados"); // Aquí debes pasar el nombre correcto

        ca.conectar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        txtNombre = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        btnboxDia = new javax.swing.JComboBox<>();
        btnboxMes = new javax.swing.JComboBox<>();
        btnboxAnio = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btrMujer = new javax.swing.JRadioButton();
        btrHombre = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        JpRegistrarUsuario = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        JpssNuevaPassword = new javax.swing.JPasswordField();
        JpEntrar = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        lblOlvidepassword = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        txtCorreo = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(0, 0, 25));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtNombre.setBackground(new java.awt.Color(0, 0, 25));
        txtNombre.setFont(new java.awt.Font("Myanmar Text", 0, 15)); // NOI18N
        txtNombre.setForeground(new java.awt.Color(255, 255, 255));
        txtNombre.setBorder(null);
        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        jPanel2.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, 250, 20));

        txtApellido.setBackground(new java.awt.Color(0, 0, 25));
        txtApellido.setFont(new java.awt.Font("Myanmar Text", 1, 15)); // NOI18N
        txtApellido.setForeground(new java.awt.Color(255, 255, 255));
        txtApellido.setBorder(null);
        txtApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApellidoActionPerformed(evt);
            }
        });
        jPanel2.add(txtApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 150, 260, 20));

        btnboxDia.setBackground(new java.awt.Color(0, 0, 38));
        btnboxDia.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        btnboxDia.setForeground(new java.awt.Color(255, 255, 255));
        btnboxDia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        btnboxDia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnboxDiaActionPerformed(evt);
            }
        });
        jPanel2.add(btnboxDia, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 240, 138, -1));

        btnboxMes.setBackground(new java.awt.Color(0, 0, 38));
        btnboxMes.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        btnboxMes.setForeground(new java.awt.Color(255, 255, 255));
        btnboxMes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ene  ", "Feb  ", "Mar  ", "Abr  ", "May  ", "Jun  ", "Jul  ", "Ago  ", "Sep  ", "Oct  ", "Nov  ", "Dic  " }));
        btnboxMes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnboxMesActionPerformed(evt);
            }
        });
        jPanel2.add(btnboxMes, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 240, 130, -1));

        btnboxAnio.setBackground(new java.awt.Color(0, 0, 38));
        btnboxAnio.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        btnboxAnio.setForeground(new java.awt.Color(255, 255, 255));
        btnboxAnio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1905  ", "1906  ", "1907  ", "1908  ", "1909  ", "1910  ", "1911  ", "1912  ", "1913  ", "1914  ", "1915  ", "1916  ", "1917  ", "1918  ", "1919  ", "1920  ", "1921  ", "1922  ", "1923  ", "1924  ", "1925  ", "1926  ", "1927  ", "1928  ", "1929  ", "1930  ", "1931  ", "1932  ", "1933  ", "1934  ", "1935  ", "1936  ", "1937  ", "1938  ", "1939  ", "1940  ", "1941  ", "1942  ", "1943  ", "1944  ", "1945  ", "1946  ", "1947  ", "1948  ", "1949  ", "1950  ", "1951  ", "1952  ", "1953  ", "1954  ", "1955  ", "1956  ", "1957  ", "1958  ", "1959  ", "1960  ", "1961  ", "1962  ", "1963  ", "1964  ", "1965  ", "1966  ", "1967  ", "1968  ", "1969  ", "1970  ", "1971  ", "1972  ", "1973  ", "1974  ", "1975  ", "1976  ", "1977  ", "1978  ", "1979  ", "1980  ", "1981  ", "1982  ", "1983  ", "1984  ", "1985  ", "1986  ", "1987  ", "1988  ", "1989  ", "1990  ", "1991  ", "1992  ", "1993  ", "1994  ", "1995  ", "1996  ", "1997  ", "1998  ", "1999  ", "2000  ", "2001  ", "2002  ", "2003  ", "2004  ", "2005  ", "2006  ", "2007  ", "2008  ", "2009  ", "2010  ", "2011  ", "2012  ", "2013  ", "2014  ", "2015  ", "2016  ", "2017  ", "2018  ", "2019  ", "2020  ", "2021  ", "2022  ", "2023  ", "2024  ", "2025  " }));
        btnboxAnio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnboxAnioActionPerformed(evt);
            }
        });
        jPanel2.add(btnboxAnio, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 240, 121, -1));

        jLabel1.setFont(new java.awt.Font("Myanmar Text", 1, 15)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 204, 0));
        jLabel1.setText("Fecha de Naciemiento:");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 200, 190, -1));
        jLabel1.getAccessibleContext().setAccessibleName("Fecha de Naciemiento ");

        jLabel2.setFont(new java.awt.Font("Myanmar Text", 1, 15)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 204, 0));
        jLabel2.setText("Género:");
        jLabel2.setMaximumSize(new java.awt.Dimension(57, 30));
        jLabel2.setMinimumSize(new java.awt.Dimension(58, 30));
        jLabel2.setPreferredSize(new java.awt.Dimension(57, 30));
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 290, 70, -1));

        btrMujer.setBackground(new java.awt.Color(0, 0, 25));
        buttonGroup1.add(btrMujer);
        btrMujer.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        btrMujer.setForeground(new java.awt.Color(255, 255, 255));
        btrMujer.setText("Mujer");
        btrMujer.setToolTipText("");
        btrMujer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btrMujerActionPerformed(evt);
            }
        });
        jPanel2.add(btrMujer, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 320, -1, -1));

        btrHombre.setBackground(new java.awt.Color(0, 0, 25));
        buttonGroup1.add(btrHombre);
        btrHombre.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        btrHombre.setForeground(new java.awt.Color(255, 255, 255));
        btrHombre.setText("Hombre");
        btrHombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btrHombreActionPerformed(evt);
            }
        });
        jPanel2.add(btrHombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 320, 90, -1));

        jLabel3.setFont(new java.awt.Font("Myanmar Text", 1, 15)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 204, 0));
        jLabel3.setText("Nombre:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, 110, -1));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 170, 260, 20));
        jPanel2.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 160, -1, -1));
        jPanel2.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, 250, 10));
        jPanel2.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 490, 480, 20));

        JpRegistrarUsuario.setBackground(new java.awt.Color(196, 196, 25));
        JpRegistrarUsuario.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        JpRegistrarUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        JpRegistrarUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JpRegistrarUsuarioMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                JpRegistrarUsuarioMouseExited(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Myanmar Text", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Registrar");

        javax.swing.GroupLayout JpRegistrarUsuarioLayout = new javax.swing.GroupLayout(JpRegistrarUsuario);
        JpRegistrarUsuario.setLayout(JpRegistrarUsuarioLayout);
        JpRegistrarUsuarioLayout.setHorizontalGroup(
            JpRegistrarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JpRegistrarUsuarioLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        JpRegistrarUsuarioLayout.setVerticalGroup(
            JpRegistrarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JpRegistrarUsuarioLayout.createSequentialGroup()
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.add(JpRegistrarUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 540, 150, 30));

        jPanel3.setBackground(new java.awt.Color(102, 102, 102));
        jPanel3.setPreferredSize(new java.awt.Dimension(1030, 240));

        jLabel11.setBackground(new java.awt.Color(0, 0, 51));
        jLabel11.setFont(new java.awt.Font("Myanmar Text", 1, 25)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Crear cuenta");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(232, 232, 232)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 445, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLabel11.getAccessibleContext().setAccessibleName("Crear cuenta");

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 1030, 90));

        JpssNuevaPassword.setBackground(new java.awt.Color(0, 0, 25));
        JpssNuevaPassword.setFont(new java.awt.Font("Myanmar Text", 1, 14)); // NOI18N
        JpssNuevaPassword.setForeground(new java.awt.Color(255, 255, 255));
        JpssNuevaPassword.setText("jPasswordField1");
        JpssNuevaPassword.setBorder(null);
        JpssNuevaPassword.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                JpssNuevaPasswordCaretUpdate(evt);
            }
        });
        JpssNuevaPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JpssNuevaPasswordActionPerformed(evt);
            }
        });
        jPanel2.add(JpssNuevaPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 470, 480, 20));

        JpEntrar.setBackground(new java.awt.Color(76, 121, 255));
        JpEntrar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        JpEntrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JpEntrarMouseClicked(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Myanmar Text", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Entrar");

        javax.swing.GroupLayout JpEntrarLayout = new javax.swing.GroupLayout(JpEntrar);
        JpEntrar.setLayout(JpEntrarLayout);
        JpEntrarLayout.setHorizontalGroup(
            JpEntrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JpEntrarLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );
        JpEntrarLayout.setVerticalGroup(
            JpEntrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JpEntrarLayout.createSequentialGroup()
                .addComponent(jLabel7)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel2.add(JpEntrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 540, 150, 30));

        lblOlvidepassword.setFont(new java.awt.Font("Myanmar Text", 3, 12)); // NOI18N
        lblOlvidepassword.setForeground(new java.awt.Color(0, 153, 255));
        lblOlvidepassword.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblOlvidepassword.setText("Olvide mi contraseña");
        lblOlvidepassword.setToolTipText("Recuperer Contraseña");
        lblOlvidepassword.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblOlvidepassword.setMaximumSize(new java.awt.Dimension(118, 23));
        lblOlvidepassword.setMinimumSize(new java.awt.Dimension(118, 23));
        lblOlvidepassword.setPreferredSize(new java.awt.Dimension(118, 23));
        lblOlvidepassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblOlvidepasswordMouseClicked(evt);
            }
        });
        jPanel2.add(lblOlvidepassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 540, 120, -1));
        jPanel2.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 560, 180, 10));
        jPanel2.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 410, 480, 10));

        txtCorreo.setBackground(new java.awt.Color(0, 0, 25));
        txtCorreo.setFont(new java.awt.Font("Myanmar Text", 1, 15)); // NOI18N
        txtCorreo.setForeground(new java.awt.Color(255, 255, 255));
        txtCorreo.setToolTipText("Correo");
        txtCorreo.setBorder(null);
        txtCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCorreoActionPerformed(evt);
            }
        });
        jPanel2.add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 390, 590, 20));

        jLabel6.setFont(new java.awt.Font("Myanmar Text", 1, 15)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 204, 0));
        jLabel6.setText("Correo:");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 350, 70, -1));

        jLabel8.setFont(new java.awt.Font("Myanmar Text", 1, 15)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 204, 0));
        jLabel8.setText("Contraseña:");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 440, -1, -1));

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestion_ingresos_radio_kat/Imegenes/Iconos/local_taxi_24dp_E3E3E3_FILL0_wght400_GRAD0_opsz24.png"))); // NOI18N
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 500, 130, 117));

        jLabel4.setFont(new java.awt.Font("Myanmar Text", 1, 15)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 204, 0));
        jLabel4.setText("Apellido:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 110, 100, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 897, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 621, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        txtNombre.setText("");

    }//GEN-LAST:event_txtNombreActionPerformed

    private void txtApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellidoActionPerformed

        txtApellido.setText("");

    }//GEN-LAST:event_txtApellidoActionPerformed

    private void btnboxDiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnboxDiaActionPerformed


    }//GEN-LAST:event_btnboxDiaActionPerformed

    private void btnboxMesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnboxMesActionPerformed


    }//GEN-LAST:event_btnboxMesActionPerformed

    private void btnboxAnioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnboxAnioActionPerformed

    }//GEN-LAST:event_btnboxAnioActionPerformed

    private void btrMujerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btrMujerActionPerformed


    }//GEN-LAST:event_btrMujerActionPerformed

    private void btrHombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btrHombreActionPerformed
    }//GEN-LAST:event_btrHombreActionPerformed


    private void JpRegistrarUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JpRegistrarUsuarioMouseClicked

        // Obtener datos de los campos de texto
        String nombre = txtNombre.getText().trim();
        String apellido = txtApellido.getText().trim();
        String correo = txtCorreo.getText().trim();
        String contrasena = new String(JpssNuevaPassword.getPassword()).trim();

        // Obtener género seleccionado
        String genero = "";
        if (btrHombre.isSelected()) {
            genero = "Masculino";
        } else if (btrMujer.isSelected()) {
            genero = "Femenino";
        }

        // Validar campos vacíos
        if (nombre.isEmpty() || apellido.isEmpty() || contrasena.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Todos los campos son obligatorios.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Validar que nombre y apellido no contengan números
        if (!nombre.matches("[a-zA-ZáéíóúÁÉÍÓÚñÑ\\s]+") || !apellido.matches("[a-zA-ZáéíóúÁÉÍÓÚñÑ\\s]+")) {
            JOptionPane.showMessageDialog(this, "El nombre y el apellido no deben contener números ni caracteres especiales.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (correo.isEmpty() || correo.isEmpty() || contrasena.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Todos los campos son obligatorios.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (!correo.matches("^[\\w-\\.]+@([\\w-]+\\.)+[\\w-]{2,4}$")) {
            JOptionPane.showMessageDialog(this, "El correo electrónico no es válido.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Validar longitud mínima de la contraseña
        if (contrasena.length() < 6) {
            JOptionPane.showMessageDialog(this, "La contraseña debe tener al menos 6 caracteres.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Validar género
        if (genero.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Seleccione un género.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Obtener fecha de nacimiento
        try {
            // Convertir los valores seleccionados de los JComboBox a enteros
            int dia = Integer.parseInt(btnboxDia.getSelectedItem().toString().trim());  // Convertimos el String a int

            // Mapear el mes en texto a número
            String mesSeleccionado = btnboxMes.getSelectedItem().toString().trim();
            int mes = convertirMesANumero(mesSeleccionado);  // Convierte el mes a un número

            int anio = Integer.parseInt(btnboxAnio.getSelectedItem().toString().trim()); // Convertimos el String a int

            // Verificar si el mes es válido
            if (mes == -1) {
                JOptionPane.showMessageDialog(this, "Mes seleccionado no es válido.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            // Crear instancia del controlador
            CrearCuentaControlador controlador = new CrearCuentaControlador("usuariosinvitados");

            // Validar si el usuario ya existe
            if (controlador.existeUsuario(nombre, apellido)) {
                JOptionPane.showMessageDialog(this, "El usuario ya existe.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            // Intentar registrar al usuario
            boolean registrado = controlador.registrarInvitado(nombre, apellido, correo, dia, mes, anio, genero, contrasena);

            if (registrado) {
                JOptionPane.showMessageDialog(this, "Cuenta creada con éxito.");
                this.dispose(); // Cierra la ventana actual (opcional)
            } else {
                JOptionPane.showMessageDialog(this, "Error al crear la cuenta.", "Error", JOptionPane.ERROR_MESSAGE);
            }

        } catch (NumberFormatException e) {
            // Si se produce un error en la conversión de los valores numéricos
            JOptionPane.showMessageDialog(this, "Por favor, ingresa valores válidos para la fecha.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

// Método para convertir el nombre del mes a un número
    private int convertirMesANumero(String mes) {
        switch (mes) {
            case "Ene":
                return 1;
            case "Feb":
                return 2;
            case "Mar":
                return 3;
            case "Abr":
                return 4;
            case "May":
                return 5;
            case "Jun":
                return 6;
            case "Jul":
                return 7;
            case "Ago":
                return 8;
            case "Sep":
                return 9;
            case "Oct":
                return 10;
            case "Nov":
                return 11;
            case "Dic":
                return 12;
            default:
                return -1; // Mes inválido
        }
    }//GEN-LAST:event_JpRegistrarUsuarioMouseClicked


    private void JpRegistrarUsuarioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JpRegistrarUsuarioMouseExited

    }//GEN-LAST:event_JpRegistrarUsuarioMouseExited

    private void JpssNuevaPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JpssNuevaPasswordActionPerformed
        JpssNuevaPassword.setText("");


    }//GEN-LAST:event_JpssNuevaPasswordActionPerformed

    private void JpssNuevaPasswordCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_JpssNuevaPasswordCaretUpdate
        // TODO add your handling code here:
    }//GEN-LAST:event_JpssNuevaPasswordCaretUpdate


    private void JpEntrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JpEntrarMouseClicked
        String nombre = txtNombre.getText().trim();
        String apellido = txtApellido.getText().trim();
        String correo = txtCorreo.getText().trim();
        String contrasena = new String(JpssNuevaPassword.getPassword()).trim();

        // Validar campos vacíos
        if (nombre.isEmpty() || apellido.isEmpty() || contrasena.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Debe completar todos los campos.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Validar nombre y apellido sin números
        if (!nombre.matches("[a-zA-ZáéíóúÁÉÍÓÚñÑ\\s]+") || !apellido.matches("[a-zA-ZáéíóúÁÉÍÓÚñÑ\\s]+")) {
            JOptionPane.showMessageDialog(this, "Nombre y apellido no deben contener números o símbolos.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
            if (correo.isEmpty() || correo.isEmpty() || contrasena.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Todos los campos son obligatorios.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (!correo.matches("^[\\w-\\.]+@([\\w-]+\\.)+[\\w-]{2,4}$")) {
            JOptionPane.showMessageDialog(this, "El correo electrónico no es válido.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Validar longitud mínima de la contraseña
        if (contrasena.length() < 6) {
            JOptionPane.showMessageDialog(this, "La contraseña debe tener al menos 6 caracteres.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        CrearCuentaControlador controlador = new CrearCuentaControlador("usuariosinvitados");

        // Verificar en base de datos si el usuario existe y coincide la contraseña
        if (controlador.validarIngreso(nombre, apellido,contrasena )) {
            JOptionPane.showMessageDialog(this, "¡Bienvenido/a " + nombre + "!", "Acceso concedido", JOptionPane.INFORMATION_MESSAGE);

            // Mostrar ventana principal
            RegistroUnidadGUI ventanaPrincipal = new RegistroUnidadGUI();
            ventanaPrincipal.setVisible(true);
            ventanaPrincipal.setLocationRelativeTo(null); // Centrar la nueva ventana

            this.dispose(); // Cierra esta ventana actual
        } else {
            JOptionPane.showMessageDialog(this, "Nombre, apellido o contraseña incorrectos.", "Acceso denegado", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_JpEntrarMouseClicked

    private void lblOlvidepasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblOlvidepasswordMouseClicked
        // Mostrar ventana 
        RecuperarPasswordGUI ventana = new RecuperarPasswordGUI();
        ventana.setVisible(true);
        ventana.setLocationRelativeTo(null); // Centrar la nueva ventana
        this.dispose();


    }//GEN-LAST:event_lblOlvidepasswordMouseClicked

    private void txtCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCorreoActionPerformed
        txtCorreo.setText("");

    }//GEN-LAST:event_txtCorreoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CrearCuentaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CrearCuentaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CrearCuentaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CrearCuentaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CrearCuentaGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JpEntrar;
    private javax.swing.JPanel JpRegistrarUsuario;
    private javax.swing.JPasswordField JpssNuevaPassword;
    private javax.swing.JComboBox<String> btnboxAnio;
    private javax.swing.JComboBox<String> btnboxDia;
    private javax.swing.JComboBox<String> btnboxMes;
    private javax.swing.JRadioButton btrHombre;
    private javax.swing.JRadioButton btrMujer;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JLabel lblOlvidepassword;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
