/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gestion_ingresos_radio_kat.UI;

import gestion_ingresos_radio_kat.UI.Propietarios.Comisiones.Logica.Modelo.AccesoDatos.Controladores_Vista_Logica.LoginControlador;
import gestion_ingresos_radio_kat.UI.RegistroUnidadGUI;
import gestion_ingresos_radio_kat.UI.CrearCuentaGUI;

import java.awt.Color;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

public class LoginUI extends javax.swing.JFrame {

    LoginControlador cx;

    public LoginUI() {
        initComponents();
        cx = new LoginControlador("datoslogin");
        cx.conectar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Backgraund = new javax.swing.JPanel();
        lblpass = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        txtNombre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        pss = new javax.swing.JPasswordField();
        JpEntrar = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        JpCrearCuenta = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setResizable(false);

        Backgraund.setBackground(new java.awt.Color(255, 255, 255));
        Backgraund.setPreferredSize(new java.awt.Dimension(800, 500));
        Backgraund.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblpass.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        lblpass.setForeground(new java.awt.Color(0, 0, 0));
        lblpass.setText("PASSWORD ");
        Backgraund.add(lblpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, 200, -1));
        Backgraund.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 330, 300, -1));
        Backgraund.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, 300, -1));

        txtNombre.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        txtNombre.setForeground(new java.awt.Color(204, 204, 204));
        txtNombre.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        txtNombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtNombreMousePressed(evt);
            }
        });
        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        Backgraund.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, 300, 30));

        jLabel4.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("USUARIO ");
        Backgraund.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, 200, -1));

        pss.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        pss.setForeground(new java.awt.Color(204, 204, 204));
        pss.setText("jPasswordField1");
        pss.setBorder(null);
        pss.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pssMousePressed(evt);
            }
        });
        pss.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pssActionPerformed(evt);
            }
        });
        Backgraund.add(pss, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, 300, 30));

        JpEntrar.setBackground(new java.awt.Color(68, 122, 156));
        JpEntrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        JpEntrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JpEntrarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                JpEntrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                JpEntrarMouseExited(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("ENTRAR");

        javax.swing.GroupLayout JpEntrarLayout = new javax.swing.GroupLayout(JpEntrar);
        JpEntrar.setLayout(JpEntrarLayout);
        JpEntrarLayout.setHorizontalGroup(
            JpEntrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JpEntrarLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );
        JpEntrarLayout.setVerticalGroup(
            JpEntrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JpEntrarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Backgraund.add(JpEntrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 380, 120, -1));

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestion_ingresos_radio_kat/Imegenes/Iconos/passkey_24dp_E3E3E3_FILL0_wght400_GRAD0_opsz24.png"))); // NOI18N
        jLabel7.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel7.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        Backgraund.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 140, -1));

        jLabel2.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("ADMINISTRADOR UNICO ");
        Backgraund.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, 280, -1));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestion_ingresos_radio_kat/Imegenes/Iconos/local_taxi_24dp_E3E3E3_FILL0_wght400_GRAD0_opsz24.png"))); // NOI18N
        Backgraund.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(522, 70, 370, 117));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestion_ingresos_radio_kat/Imegenes/Iconos/image1_0.jpg"))); // NOI18N
        Backgraund.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 0, 370, 560));

        JpCrearCuenta.setBackground(new java.awt.Color(25, 137, 54));
        JpCrearCuenta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        JpCrearCuenta.setPreferredSize(new java.awt.Dimension(110, 29));
        JpCrearCuenta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JpCrearCuentaMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                JpCrearCuentaMouseExited(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("CREAR CUENTA");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout JpCrearCuentaLayout = new javax.swing.GroupLayout(JpCrearCuenta);
        JpCrearCuenta.setLayout(JpCrearCuentaLayout);
        JpCrearCuentaLayout.setHorizontalGroup(
            JpCrearCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JpCrearCuentaLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel6)
                .addContainerGap(14, Short.MAX_VALUE))
        );
        JpCrearCuentaLayout.setVerticalGroup(
            JpCrearCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JpCrearCuentaLayout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(15, 15, 15))
        );

        Backgraund.add(JpCrearCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 440, 150, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Backgraund, javax.swing.GroupLayout.DEFAULT_SIZE, 892, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Backgraund, javax.swing.GroupLayout.DEFAULT_SIZE, 561, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed


    }//GEN-LAST:event_txtNombreActionPerformed


    private void JpEntrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JpEntrarMouseEntered


    }//GEN-LAST:event_JpEntrarMouseEntered


    private void pssActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pssActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pssActionPerformed

    private void txtNombreMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNombreMousePressed

        if (txtNombre.getText().equals("Ingrese su nombre")) {
            txtNombre.setText("");
            txtNombre.setForeground(Color.black);
        }
        if (String.valueOf(pss.getPassword()).isEmpty()) {
            pss.setText("********");
            pss.setForeground(Color.gray);
        }


    }//GEN-LAST:event_txtNombreMousePressed

    private void pssMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pssMousePressed
        if (String.valueOf(pss.getPassword()).equals("********")) {
            pss.setText("");
            pss.setForeground(Color.black);
        }
        if (txtNombre.getText().isEmpty()) {
            txtNombre.setText("Ingrese su nombre");
            txtNombre.setForeground(Color.gray);
        }
    }//GEN-LAST:event_pssMousePressed


    private void JpEntrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JpEntrarMouseClicked
        try {
            String nombre = txtNombre.getText();
            String passIngresada = String.valueOf(pss.getPassword());

            // Verificar si la contraseña está vacía
            if (passIngresada.trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "La contraseña no puede estar vacía", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            // Validar contraseña antes de proceder
            if (!passIngresada.equals("JGFF")) {
                JOptionPane.showMessageDialog(this, "Contraseña incorrecta", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            // Si pasa las validaciones anteriores, se permite continuar
            String checkQuery = "SELECT * FROM administrador WHERE Nombre = ?";
            PreparedStatement checkSt = cx.conectar().prepareStatement(checkQuery);
            checkSt.setString(1, nombre);
            ResultSet rs = checkSt.executeQuery();

            if (rs.next()) {
                // El usuario ya existe y la contraseña es válida
                System.out.println("Usuario validado: " + nombre);
                RegistroUnidadGUI registroUnidad = new RegistroUnidadGUI();
                registroUnidad.setVisible(true);
                this.dispose();
            } else {
                // Registrar nuevo usuario con contraseña válida
                int inserted = registrarUsuario(nombre, passIngresada);
                if (inserted > 0) {
                    System.out.println("Nuevo usuario " + nombre + " registrado exitosamente.");
                    RegistroUnidadGUI registroUnidad = new RegistroUnidadGUI();
                    registroUnidad.setVisible(true);
                    this.dispose();
                } else {
                    JOptionPane.showMessageDialog(this, "Error al registrar usuario", "Error", JOptionPane.ERROR_MESSAGE);
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(LoginUI.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Error de conexión con la base de datos: " + ex.getMessage(),
                    "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_JpEntrarMouseClicked

// Método para registrar al usuario que se logueó
    private int registrarUsuario(String nombre, String password) throws SQLException {
        String insertQuery = "INSERT INTO administrador (Nombre, password) VALUES (?, ?)";
        PreparedStatement insertSt = cx.conectar().prepareStatement(insertQuery);
        insertSt.setString(1, nombre);
        insertSt.setString(2, password);
        return insertSt.executeUpdate();
    }


    private void JpEntrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JpEntrarMouseExited
        JpEntrar.setBackground(new Color(0, 134, 190)); // Restaurar color original al salir


    }//GEN-LAST:event_JpEntrarMouseExited

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel6MouseClicked

    private void JpCrearCuentaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JpCrearCuentaMouseClicked
        // TODO add your handling code here:
        CrearCuentaGUI crearCuenta = new CrearCuentaGUI(); // Instanciar la ventana de crear cuenta
        crearCuenta.setVisible(true); // Mostrarla
        crearCuenta.setLocationRelativeTo(null); // Centrar la ventana
        this.dispose(); // Cerrar la ventana actual (LoginUI)
   

    }//GEN-LAST:event_JpCrearCuentaMouseClicked

    private void JpCrearCuentaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JpCrearCuentaMouseExited
        JpEntrar.setBackground(new Color(0, 134, 190)); // Restaurar color original al salir
    }//GEN-LAST:event_JpCrearCuentaMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Backgraund;
    private javax.swing.JPanel JpCrearCuenta;
    private javax.swing.JPanel JpEntrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblpass;
    private javax.swing.JPasswordField pss;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
