package gestion_ingresos_radio_kat.UI;

import gestion_ingresos_radio_kat.UI.Propietarios.Comisiones.Logica.Modelo.AccesoDatos.Controladores_Vista_Logica.CrearCuentaControlador;

import java.util.Properties;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.mail.Message;
import javax.mail.MessagingException;
import javax.mail.NoSuchProviderException;
import javax.mail.PasswordAuthentication;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.AddressException;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
import javax.swing.*;

/**
 *
 * @author User
 */
public class RecuperarPasswordGUI extends javax.swing.JFrame {

    private static String emailFrom = "radiokatcatemaco@gmail.com";
    private static String passwordFrom = "opuk aepx bdnn zzcn";
    private String emailTo;
    private String subject;
    private String content;

    private Properties mProperties;
    private Session mSession;
    private MimeMessage mCorreo;

    public RecuperarPasswordGUI() {
        initComponents();
        mProperties = new Properties();
        this.setLocationRelativeTo(null);

    }

    private void createEmail() {
        emailTo = txtDireccionCorreo.getText().trim();
        subject = txtSubject.getText().trim();
        content = JpRecuperarPassword.getText().trim();

        // Simple mail transfer protocol
        mProperties.put("mail.smtp.host", "smtp.gmail.com");
        mProperties.put("mail.smtp.ssl.trust", "smtp.gmail.com");
        mProperties.setProperty("mail.smtp.starttls.enable", "true");
        mProperties.setProperty("mail.smtp.port", "587");
        mProperties.setProperty("mail.smtp.user", emailFrom);
        mProperties.setProperty("mail.smtp.ssl.protocols", "TLSv1.2");
        mProperties.setProperty("mail.smtp.auth", "true");

        mSession = Session.getDefaultInstance(mProperties);

        try {
            mCorreo = new MimeMessage(mSession);
            mCorreo.setFrom(new InternetAddress(emailFrom));
            mCorreo.setRecipient(Message.RecipientType.TO, new InternetAddress(emailTo));
            mCorreo.setSubject(subject);
            mCorreo.setText(content, "ISO-8859-1", "html");

        } catch (AddressException ex) {
            Logger.getLogger(RecuperarPasswordGUI.class.getName()).log(Level.SEVERE, null, ex);
        } catch (MessagingException ex) {
            Logger.getLogger(RecuperarPasswordGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void sendEmail() {
        try {
            Transport mTransport = mSession.getTransport("smtp");
            mTransport.connect(emailFrom, passwordFrom);
            mTransport.sendMessage(mCorreo, mCorreo.getRecipients(Message.RecipientType.TO));
            mTransport.close();

            JOptionPane.showMessageDialog(null, "Correo enviado");
        } catch (NoSuchProviderException ex) {
            Logger.getLogger(RecuperarPasswordGUI.class.getName()).log(Level.SEVERE, null, ex);
        } catch (MessagingException ex) {
            Logger.getLogger(RecuperarPasswordGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private boolean enviarCorreo(String destinatario, String nuevaPassword) {
        final String remitente = "radiokatcatemaco@gmail.com";
        final String clave = "opuk aepx bdnn zzcn";

        Properties props = new Properties();
        props.put("mail.smtp.auth", "true");
        props.put("mail.smtp.starttls.enable", "true");
        props.put("mail.smtp.host", "smtp.gmail.com");
        props.put("mail.smtp.port", "587");
        props.put("mail.smtp.ssl.protocols", "TLSv1.2");

        Session session = Session.getInstance(props, new javax.mail.Authenticator() {
            protected PasswordAuthentication getPasswordAuthentication() {
                return new PasswordAuthentication(remitente, clave);
            }
        });

        try {
            Message message = new MimeMessage(session);
            message.setFrom(new InternetAddress(remitente));
            message.setRecipients(Message.RecipientType.TO, InternetAddress.parse(destinatario));
            message.setSubject("Recuperación de contraseña");
            message.setText("Hola,\n\nTu nueva contraseña es: " + nuevaPassword + "\n\nSaludos,\nRadio Kat");

            Transport.send(message);
            return true;
        } catch (MessagingException e) {
            e.printStackTrace();
            return false;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        txtSubject = new javax.swing.JLabel();
        JpRecuperarPassword = new javax.swing.JPasswordField();
        jSeparator1 = new javax.swing.JSeparator();
        JpRecuperar = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtDireccionCorreo = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        btnRegresar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 25));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(102, 102, 102));
        jPanel3.setPreferredSize(new java.awt.Dimension(1030, 240));

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Myanmar Text", 1, 25)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText(" Recuperar cuenta");
        jLabel11.setMaximumSize(new java.awt.Dimension(205, 48));
        jLabel11.setMinimumSize(new java.awt.Dimension(205, 48));
        jLabel11.setPreferredSize(new java.awt.Dimension(206, 48));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(252, 252, 252)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 445, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(193, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 890, 90));

        txtSubject.setForeground(new java.awt.Color(0, 0, 0));
        txtSubject.setText("Recuperar password   ");
        jPanel1.add(txtSubject, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 100, 351, 90));

        JpRecuperarPassword.setBackground(new java.awt.Color(0, 0, 25));
        JpRecuperarPassword.setFont(new java.awt.Font("Myanmar Text", 1, 15)); // NOI18N
        JpRecuperarPassword.setForeground(new java.awt.Color(255, 255, 255));
        JpRecuperarPassword.setText("jPasswordField1");
        JpRecuperarPassword.setToolTipText("Contraseña Nueva");
        JpRecuperarPassword.setBorder(null);
        jPanel1.add(JpRecuperarPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 320, 290, 40));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 360, 290, 30));

        JpRecuperar.setBackground(new java.awt.Color(0, 153, 255));
        JpRecuperar.setMinimumSize(new java.awt.Dimension(117, 30));
        JpRecuperar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JpRecuperarMouseClicked(evt);
            }
        });
        JpRecuperar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Myanmar Text", 1, 15)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Recuperar");
        jLabel3.setMaximumSize(new java.awt.Dimension(73, 30));
        jLabel3.setMinimumSize(new java.awt.Dimension(73, 30));
        jLabel3.setPreferredSize(new java.awt.Dimension(73, 30));
        JpRecuperar.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 77, 20));

        jPanel1.add(JpRecuperar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 440, 150, 40));

        txtDireccionCorreo.setBackground(new java.awt.Color(0, 0, 25));
        txtDireccionCorreo.setFont(new java.awt.Font("Myanmar Text", 1, 15)); // NOI18N
        txtDireccionCorreo.setForeground(new java.awt.Color(255, 255, 255));
        txtDireccionCorreo.setToolTipText("Direccion correo Electronico ");
        txtDireccionCorreo.setBorder(null);
        jPanel1.add(txtDireccionCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, 290, 40));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, 290, 20));

        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Contraseña");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 340, 100, -1));

        btnRegresar.setBackground(new java.awt.Color(255, 0, 0));
        btnRegresar.setFont(new java.awt.Font("Myanmar Text", 1, 15)); // NOI18N
        btnRegresar.setForeground(new java.awt.Color(255, 255, 255));
        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 440, 120, 40));

        jLabel2.setFont(new java.awt.Font("Myanmar Text", 1, 15)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 204, 0));
        jLabel2.setText("Ingresa tu correo electrónico:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, 253, 30));

        jLabel5.setFont(new java.awt.Font("Myanmar Text", 1, 15)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 204, 0));
        jLabel5.setText("Contraseña:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 290, 100, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 890, 570));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JpRecuperarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JpRecuperarMouseClicked
        String correo = txtDireccionCorreo.getText().trim();
        String nuevaContrasena = new String(JpRecuperarPassword.getPassword()).trim();

        if (correo.isEmpty() || nuevaContrasena.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Completa todos los campos.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        CrearCuentaControlador controlador = new CrearCuentaControlador("usuariosinvitados");
        controlador.conectar();

        boolean actualizado = controlador.actualizarContrasenaPorCorreo(correo, nuevaContrasena);

        if (actualizado) {
            boolean enviado = enviarCorreo(correo, nuevaContrasena);
            if (enviado) {
                JOptionPane.showMessageDialog(this, "Contraseña actualizada y enviada a tu correo.");
            } else {
                JOptionPane.showMessageDialog(this, "La contraseña fue actualizada, pero no se pudo enviar el correo.", "Aviso", JOptionPane.WARNING_MESSAGE);
            }
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "No se encontró un usuario con ese correo.", "Error", JOptionPane.ERROR_MESSAGE);
        }
        createEmail();
        sendEmail();

        RegistroUnidadGUI r = new RegistroUnidadGUI();
        r.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_JpRecuperarMouseClicked

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        CrearCuentaGUI crearCuenta = new CrearCuentaGUI(); // Instanciar la ventana de crear cuenta
        crearCuenta.setVisible(true); // Mostrarla
        crearCuenta.setLocationRelativeTo(null); // Centrar la ventana
        this.dispose(); // Cerrar la ventana actual (LoginUI)


    }//GEN-LAST:event_btnRegresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RecuperarPasswordGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RecuperarPasswordGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RecuperarPasswordGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RecuperarPasswordGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RecuperarPasswordGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JpRecuperar;
    private javax.swing.JPasswordField JpRecuperarPassword;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField txtDireccionCorreo;
    private javax.swing.JLabel txtSubject;
    // End of variables declaration//GEN-END:variables
}
