package gestion_ingresos_radio_kat.UI;

import gestion_ingresos_radio_kat.UI.Propietarios.Comisiones.Logica.Modelo.AccesoDatos.UnidadDAO;
import gestion_ingresos_radio_kat.UI.Propietarios.Comisiones.ReportesGUI;
import gestion_ingresos_radio_kat.UI.Propietarios.GestionIngresosGUI;
import gestion_ingresos_radio_kat.UI.Propietarios.RegistroTurnoGUI;
import java.awt.Color;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class RegistroUnidadGUI extends javax.swing.JFrame {

    private JPanel selectedPanel = null;

    // Variables estáticas para compartir datos con GestionIngresosGUI
    public static String ultimoTipoUnidadRegistrada = "";
    public static String ultimoNombrePropietarioRegistrado = "";

    /**
     * Creates new form RegistroUnidadGUI
     */
    public RegistroUnidadGUI() {
        initComponents();

        DefaultTableModel model = new DefaultTableModel(
                new Object[]{"Numero Placa", "Nombre Propietario", "Numero Comercial", "Numero Teléfono", "Tipo Unidad", "Estado Unidad"}, 0
        );
        jTableRegistroUnidad.setModel(model);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JpFondo = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        JpGestionIngresos = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        JpRegistroTurno = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        JpReportes = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        btnRegresar = new javax.swing.JButton();
        btnAdelante = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtNumPlaca = new javax.swing.JTextField();
        txtNombrePropietario = new javax.swing.JTextField();
        txtNumComercial = new javax.swing.JTextField();
        txtNumTelefono = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        boxTipoUnidad = new javax.swing.JComboBox<>();
        boxEstadoUnidad = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jPanel4 = new javax.swing.JPanel();
        btnRegistrarUnidad = new javax.swing.JButton();
        btnLimpiarFormulario = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableRegistroUnidad = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        btnBorrarDatoTabla = new javax.swing.JButton();
        btnBuscarUnidad = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JSeparator();
        txtBuscarPlaca = new javax.swing.JTextField();
        btnCargarDataBase = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        JpFondo.setBackground(new java.awt.Color(255, 255, 255));
        JpFondo.setPreferredSize(new java.awt.Dimension(1020, 800));
        JpFondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(29, 54, 88));
        jPanel1.setPreferredSize(new java.awt.Dimension(270, 640));

        JpGestionIngresos.setBackground(new java.awt.Color(29, 54, 88));
        JpGestionIngresos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JpGestionIngresosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                JpGestionIngresosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                JpGestionIngresosMouseExited(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Gestion Ingresos");

        javax.swing.GroupLayout JpGestionIngresosLayout = new javax.swing.GroupLayout(JpGestionIngresos);
        JpGestionIngresos.setLayout(JpGestionIngresosLayout);
        JpGestionIngresosLayout.setHorizontalGroup(
            JpGestionIngresosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JpGestionIngresosLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        JpGestionIngresosLayout.setVerticalGroup(
            JpGestionIngresosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JpGestionIngresosLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addGap(14, 14, 14))
        );

        JpRegistroTurno.setBackground(new java.awt.Color(29, 54, 88));
        JpRegistroTurno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JpRegistroTurnoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                JpRegistroTurnoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                JpRegistroTurnoMouseExited(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Registro Turno");

        javax.swing.GroupLayout JpRegistroTurnoLayout = new javax.swing.GroupLayout(JpRegistroTurno);
        JpRegistroTurno.setLayout(JpRegistroTurnoLayout);
        JpRegistroTurnoLayout.setHorizontalGroup(
            JpRegistroTurnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JpRegistroTurnoLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );
        JpRegistroTurnoLayout.setVerticalGroup(
            JpRegistroTurnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JpRegistroTurnoLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                .addGap(19, 19, 19))
        );

        JpReportes.setBackground(new java.awt.Color(29, 54, 88));
        JpReportes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JpReportesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                JpReportesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                JpReportesMouseExited(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Reportes");

        javax.swing.GroupLayout JpReportesLayout = new javax.swing.GroupLayout(JpReportes);
        JpReportes.setLayout(JpReportesLayout);
        JpReportesLayout.setHorizontalGroup(
            JpReportesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JpReportesLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(63, Short.MAX_VALUE))
        );
        JpReportesLayout.setVerticalGroup(
            JpReportesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JpReportesLayout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addGap(20, 20, 20))
        );

        jPanel5.setBackground(new java.awt.Color(29, 54, 88));

        btnRegresar.setBackground(new java.awt.Color(29, 54, 88));
        btnRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestion_ingresos_radio_kat/Imegenes/Iconos/Regresar.png"))); // NOI18N
        btnRegresar.setBorder(null);
        btnRegresar.setRolloverEnabled(true);
        btnRegresar.setSelected(true);
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        btnAdelante.setBackground(new java.awt.Color(29, 54, 88));
        btnAdelante.setForeground(new java.awt.Color(255, 255, 255));
        btnAdelante.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestion_ingresos_radio_kat/Imegenes/Iconos/adelante.png"))); // NOI18N
        btnAdelante.setText("jButton1");
        btnAdelante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdelanteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(btnRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAdelante, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAdelante, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestion_ingresos_radio_kat/Imegenes/Iconos/local_taxi_24dp_E3E3E3_FILL0_wght400_GRAD0_opsz24.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JpGestionIngresos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(JpRegistroTurno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(JpReportes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(92, 92, 92)
                .addComponent(JpGestionIngresos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addComponent(JpRegistroTurno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(JpReportes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(87, 87, 87)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(114, Short.MAX_VALUE))
        );

        JpFondo.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 750));

        jPanel2.setBackground(new java.awt.Color(68, 122, 156));
        jPanel2.setPreferredSize(new java.awt.Dimension(1030, 240));

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Registro Unidad ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(307, Short.MAX_VALUE)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 445, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(278, 278, 278))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        JpFondo.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 0, 1030, 140));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("Nombre Propietario ");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 192, -1));

        jLabel3.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("Numero placa");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 150, -1));

        jLabel4.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("Numero comercial ");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 170, -1));

        jLabel5.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("Numero Telefono");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, 150, -1));

        txtNumPlaca.setBorder(null);
        txtNumPlaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumPlacaActionPerformed(evt);
            }
        });
        jPanel3.add(txtNumPlaca, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 250, 29));

        txtNombrePropietario.setBorder(null);
        txtNombrePropietario.setPreferredSize(new java.awt.Dimension(117, 16));
        txtNombrePropietario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombrePropietarioActionPerformed(evt);
            }
        });
        jPanel3.add(txtNombrePropietario, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 250, 29));

        txtNumComercial.setBorder(null);
        txtNumComercial.setPreferredSize(new java.awt.Dimension(117, 16));
        txtNumComercial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumComercialActionPerformed(evt);
            }
        });
        jPanel3.add(txtNumComercial, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 250, 29));

        txtNumTelefono.setBorder(null);
        txtNumTelefono.setPreferredSize(new java.awt.Dimension(117, 16));
        txtNumTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumTelefonoActionPerformed(evt);
            }
        });
        jPanel3.add(txtNumTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, 250, 29));
        jPanel3.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 250, 10));
        jPanel3.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 250, 15));
        jPanel3.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 250, 10));

        boxTipoUnidad.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        boxTipoUnidad.setForeground(new java.awt.Color(0, 0, 0));
        boxTipoUnidad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Propietario unico", "Chofer externo" }));
        boxTipoUnidad.setBorder(null);
        boxTipoUnidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxTipoUnidadActionPerformed(evt);
            }
        });
        jPanel3.add(boxTipoUnidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 80, 153, -1));

        boxEstadoUnidad.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        boxEstadoUnidad.setForeground(new java.awt.Color(0, 0, 0));
        boxEstadoUnidad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Activo", "Inactivo" }));
        boxEstadoUnidad.setBorder(new javax.swing.border.MatteBorder(null));
        boxEstadoUnidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxEstadoUnidadActionPerformed(evt);
            }
        });
        jPanel3.add(boxEstadoUnidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 80, 155, -1));

        jLabel6.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Tipo de unidad");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 40, 153, -1));

        jLabel7.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Estado de la unidad");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 40, 155, -1));
        jPanel3.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 460, 250, 10));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnRegistrarUnidad.setBackground(new java.awt.Color(255, 255, 255));
        btnRegistrarUnidad.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        btnRegistrarUnidad.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrarUnidad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestion_ingresos_radio_kat/Imegenes/Iconos/Registro Unidad.png"))); // NOI18N
        btnRegistrarUnidad.setToolTipText("Registrar Unidad");
        btnRegistrarUnidad.setBorder(null);
        btnRegistrarUnidad.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegistrarUnidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarUnidadActionPerformed(evt);
            }
        });
        jPanel4.add(btnRegistrarUnidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 0, -1, 54));

        btnLimpiarFormulario.setBackground(new java.awt.Color(255, 255, 255));
        btnLimpiarFormulario.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        btnLimpiarFormulario.setForeground(new java.awt.Color(255, 255, 255));
        btnLimpiarFormulario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestion_ingresos_radio_kat/Imegenes/Iconos/LimpiarFormulario.png"))); // NOI18N
        btnLimpiarFormulario.setToolTipText("Borrar Formulario");
        btnLimpiarFormulario.setBorder(null);
        btnLimpiarFormulario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLimpiarFormulario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarFormularioActionPerformed(evt);
            }
        });
        jPanel4.add(btnLimpiarFormulario, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 0, -1, 56));

        btnCancelar.setBackground(new java.awt.Color(255, 255, 255));
        btnCancelar.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestion_ingresos_radio_kat/Imegenes/Iconos/Cancelar.png"))); // NOI18N
        btnCancelar.setToolTipText("Cancelar");
        btnCancelar.setBorder(null);
        btnCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        jPanel4.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(859, 0, -1, 56));

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 540, 960, 60));

        jTableRegistroUnidad.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Numero Placa", "Nombre Propietario", "Numero Comercial ", "Numero Telefono", "Tipo Unidad", "Estado Unidad"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableRegistroUnidad);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 200, 690, 270));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBorrarDatoTabla.setText("Borrar ");
        btnBorrarDatoTabla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarDatoTablaActionPerformed(evt);
            }
        });
        jPanel6.add(btnBorrarDatoTabla, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 10, 90, 30));

        btnBuscarUnidad.setText("Buscar");
        btnBuscarUnidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarUnidadActionPerformed(evt);
            }
        });
        jPanel6.add(btnBuscarUnidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 60, 30));
        jPanel6.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, 240, 20));

        txtBuscarPlaca.setBorder(null);
        txtBuscarPlaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarPlacaActionPerformed(evt);
            }
        });
        jPanel6.add(txtBuscarPlaca, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 240, 30));

        btnCargarDataBase.setText("Refresh");
        btnCargarDataBase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCargarDataBaseActionPerformed(evt);
            }
        });
        jPanel6.add(btnCargarDataBase, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 10, 90, 30));

        jPanel3.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 130, 680, 70));

        JpFondo.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 140, 1000, 610));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(JpFondo, javax.swing.GroupLayout.PREFERRED_SIZE, 1271, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(JpFondo, javax.swing.GroupLayout.PREFERRED_SIZE, 751, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtNumTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumTelefonoActionPerformed
        // TODO add your handling code here:


    }//GEN-LAST:event_txtNumTelefonoActionPerformed

    private void txtNumComercialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumComercialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumComercialActionPerformed

    private void txtNombrePropietarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombrePropietarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombrePropietarioActionPerformed

    private void txtNumPlacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumPlacaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumPlacaActionPerformed


    private void btnRegistrarUnidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarUnidadActionPerformed

        String numPlaca = txtNumPlaca.getText().trim();
        String nombreProp = txtNombrePropietario.getText().trim();
        String numComercial = txtNumComercial.getText().trim();
        String numTelefono = txtNumTelefono.getText().trim();
        String tipoUnidad = (String) boxTipoUnidad.getSelectedItem();
        String estadoUnidad = (String) boxEstadoUnidad.getSelectedItem();

        if (numPlaca.isEmpty() || nombreProp.isEmpty() || numComercial.isEmpty() || numTelefono.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor, completa todos los campos.", "Campos incompletos", JOptionPane.WARNING_MESSAGE);
            return;
        }

        UnidadDAO dao = new UnidadDAO();
        boolean exito = dao.registrarUnidad(numPlaca, nombreProp, numComercial, numTelefono, tipoUnidad, estadoUnidad);

        if (exito) {

            // Guardar en las variables públicas
            ultimoTipoUnidadRegistrada = tipoUnidad;
            ultimoNombrePropietarioRegistrado = nombreProp;

            javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) jTableRegistroUnidad.getModel();
            model.addRow(new Object[]{numPlaca, nombreProp, numComercial, numTelefono, tipoUnidad, estadoUnidad});
            JOptionPane.showMessageDialog(this, "Unidad registrada exitosamente.", "Registro exitoso", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "Error al registrar la unidad en la base de datos.", "Error", JOptionPane.ERROR_MESSAGE);
        }

        cargarDatosDesdeBaseDeDatos();


    }//GEN-LAST:event_btnRegistrarUnidadActionPerformed

    //depuracion 

    private void btnLimpiarFormularioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarFormularioActionPerformed
        // TODO add your handling code here:
        txtNumPlaca.setText("");
        txtNombrePropietario.setText("");
        txtNumComercial.setText("");
        txtNumTelefono.setText("");
        boxTipoUnidad.setSelectedIndex(0);
        boxEstadoUnidad.setSelectedIndex(0);
    }//GEN-LAST:event_btnLimpiarFormularioActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        System.exit(0);

    }//GEN-LAST:event_btnCancelarActionPerformed

    private void JpGestionIngresosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JpGestionIngresosMouseEntered
        if (selectedPanel != JpGestionIngresos) {
            JpGestionIngresos.setBackground(new Color(68, 122, 156));
        }

    }//GEN-LAST:event_JpGestionIngresosMouseEntered

    private void JpGestionIngresosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JpGestionIngresosMouseClicked
        // TODO add your handling code here:
        GestionIngresosGUI ingresos = new GestionIngresosGUI();
        ingresos.setVisible(true);

        // Cerrar la ventana actual
        this.dispose();

        if (selectedPanel != null) {
            selectedPanel.setBackground(new Color(44, 90, 120)); // Color original al deseleccionar
        }
        selectedPanel = JpGestionIngresos;
        JpGestionIngresos.setBackground(new Color(68, 122, 156));
        JOptionPane.showMessageDialog(this, "Gestión de ingresos seleccionada.", "Información", JOptionPane.INFORMATION_MESSAGE);

    }//GEN-LAST:event_JpGestionIngresosMouseClicked


    private void JpRegistroTurnoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JpRegistroTurnoMouseClicked

        // TODO add your handling code here:
        RegistroTurnoGUI ingresos = new RegistroTurnoGUI();
        ingresos.setVisible(true);

        // Cerrar la ventana actual
        this.dispose();

        if (selectedPanel != null) {
            selectedPanel.setBackground(new Color(44, 90, 120));
        }
        selectedPanel = JpRegistroTurno;
        JpRegistroTurno.setBackground(new Color(68, 122, 156));
        JOptionPane.showMessageDialog(this, "Registro de turno seleccionado.", "Información", JOptionPane.INFORMATION_MESSAGE);


    }//GEN-LAST:event_JpRegistroTurnoMouseClicked

    private void JpRegistroTurnoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JpRegistroTurnoMouseEntered
        if (selectedPanel != JpRegistroTurno) {
            JpRegistroTurno.setBackground(new Color(68, 122, 156));
        }

    }//GEN-LAST:event_JpRegistroTurnoMouseEntered

    private void JpReportesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JpReportesMouseClicked
        // TODO add your handling code here:
        ReportesGUI rep = new ReportesGUI();
        rep.setVisible(true);

        // Cerrar la ventana actual
        this.dispose();

        if (selectedPanel != null) {
            selectedPanel.setBackground(new Color(44, 90, 120));
        }
        selectedPanel = JpReportes;
        JpReportes.setBackground(new Color(68, 122, 156));
        JOptionPane.showMessageDialog(this, "Reporte generado.", "Información", JOptionPane.INFORMATION_MESSAGE);

    }//GEN-LAST:event_JpReportesMouseClicked


    private void JpReportesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JpReportesMouseEntered
        if (selectedPanel != JpReportes) {
            JpReportes.setBackground(new Color(68, 122, 156));
        }

    }//GEN-LAST:event_JpReportesMouseEntered

    private void JpRegistroTurnoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JpRegistroTurnoMouseExited
        if (selectedPanel != JpRegistroTurno) {
            JpRegistroTurno.setBackground(new Color(44, 90, 120));
        }


    }//GEN-LAST:event_JpRegistroTurnoMouseExited

    private void JpGestionIngresosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JpGestionIngresosMouseExited
        if (selectedPanel != JpGestionIngresos) {
            JpGestionIngresos.setBackground(new Color(44, 90, 120));
        }
    }//GEN-LAST:event_JpGestionIngresosMouseExited

    private void JpReportesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JpReportesMouseExited
        if (selectedPanel != JpReportes) {
            JpReportes.setBackground(new Color(44, 90, 120));
        }
    }//GEN-LAST:event_JpReportesMouseExited

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed

        LoginUI login = new LoginUI();
        login.setVisible(true);

        // Cerrar la ventana actual
        this.dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnAdelanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdelanteActionPerformed
        // TODO add your handling code here:
        GestionIngresosGUI ingresos = new GestionIngresosGUI();
        ingresos.setVisible(true);

        // Cerrar la ventana actual
        this.dispose();
    }//GEN-LAST:event_btnAdelanteActionPerformed

    private void boxTipoUnidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxTipoUnidadActionPerformed
        // TODO add your handling code here:
        // boxTipoUnidad.addItem("Propiario unico");
        // boxTipoUnidad.addItem("Chofer externo");
    }//GEN-LAST:event_boxTipoUnidadActionPerformed

    private void boxEstadoUnidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxEstadoUnidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boxEstadoUnidadActionPerformed

    private void btnBuscarUnidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarUnidadActionPerformed
        String termino = txtBuscarPlaca.getText().trim().toLowerCase();

        if (termino.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese una placa o nombre de propietario para buscar.");
            return;
        }

        DefaultTableModel model = (DefaultTableModel) jTableRegistroUnidad.getModel();
        boolean encontrado = false;

        for (int i = 0; i < model.getRowCount(); i++) {
            String placa = model.getValueAt(i, 0).toString().toLowerCase(); // columna placa
            String nombrePropietario = model.getValueAt(i, 1).toString().toLowerCase(); // columna nombre

            if (placa.contains(termino) || nombrePropietario.contains(termino)) {
                jTableRegistroUnidad.setRowSelectionInterval(i, i);
                jTableRegistroUnidad.scrollRectToVisible(jTableRegistroUnidad.getCellRect(i, 0, true));
                encontrado = true;
                break;
            }
        }

        if (!encontrado) {
            JOptionPane.showMessageDialog(this,
                    "No se encontró ninguna unidad con esa placa o nombre.",
                    "Resultado de búsqueda",
                    JOptionPane.INFORMATION_MESSAGE);
        }


    }//GEN-LAST:event_btnBuscarUnidadActionPerformed

    ///Codigo de respaldo 
    /*
       private void btnBuscarUnidadActionPerformed(java.awt.event.ActionEvent evt) {                                                
        // TODO add your handling code here:
        String placaBuscada = txtBuscarPlaca.getText().trim();
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) jTableRegistroUnidad.getModel();

        boolean encontrado = false;
        for (int i = 0; i < model.getRowCount(); i++) {
            if (model.getValueAt(i, 0).toString().equalsIgnoreCase(placaBuscada)) {
                jTableRegistroUnidad.setRowSelectionInterval(i, i);
                encontrado = true;
                break;
            }
        }

        if (!encontrado) {
            JOptionPane.showMessageDialog(this, "No se encontró ninguna unidad con esa placa.", "Resultado de búsqueda", JOptionPane.INFORMATION_MESSAGE);
        }

    }                                               

    
     */
//IMPLEMENTACION QUE FUNCIONA 
    /*
       private void btnBuscarUnidadActionPerformed(java.awt.event.ActionEvent evt) {                                                
        // TODO add your handling code here:
        String placaBuscada = txtBuscarPlaca.getText().trim();
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) jTableRegistroUnidad.getModel();

        boolean encontrado = false;
        for (int i = 0; i < model.getRowCount(); i++) {
            if (model.getValueAt(i, 0).toString().equalsIgnoreCase(placaBuscada)) {
                jTableRegistroUnidad.setRowSelectionInterval(i, i);
                encontrado = true;
                break;
            }
        }

        if (!encontrado) {
            JOptionPane.showMessageDialog(this, "No se encontró ninguna unidad con esa placa.", "Resultado de búsqueda", JOptionPane.INFORMATION_MESSAGE);
        }

    }            
     */
    //Implementar busqueda´ por nombre 
    /*
     String termino = txtBusqueda.getText().trim().toLowerCase();

        if (termino.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Escribe el nombre del propietario o la placa a buscar.");
            return;
        }

        UnidadDAO unidadDAO = new UnidadDAO();
        List<Object[]> unidades = unidadDAO.obtenerUnidades();

        boolean encontrado = false;

        for (Object[] unidad : unidades) {
            String placa = ((String) unidad[0]).toLowerCase();
            String nombrePropietario = ((String) unidad[1]).toLowerCase();
            String tipoUnidad = (String) unidad[4];

            if (placa.contains(termino) || nombrePropietario.contains(termino)) {
                double ingresosBrutos = 0.0;
                double comision = CalculoIngresos.calcularComisionTotal(ingresosBrutos, tipoUnidad);
                double ganancia = CalculoIngresos.calcularGananciaPropietario(ingresosBrutos, comision);

                // Agregar fila a la tabla
                model.addRow(new Object[]{
                    "", // Fecha
                    tipoUnidad,
                    unidad[1], // Propietario (nombre original con mayúsculas)
                    "", // Ingresos Brutos vacío
                    tipoUnidad.equalsIgnoreCase("Propietario unico") ? "10%" : "5%",
                    String.format("%.2f", comision),
                    String.format("%.2f", ganancia)
                });

                // Mostrar mensaje según tipo
                if (tipoUnidad.equalsIgnoreCase("Propietario unico")) {
                    JOptionPane.showMessageDialog(this,
                            "Propietario único encontrado.\nAsignarle 10% de comisión e ingresar su ingreso bruto correspondiente.",
                            "Propietario único", JOptionPane.INFORMATION_MESSAGE);
                } else if (tipoUnidad.equalsIgnoreCase("Chofer externo")) {
                    JOptionPane.showMessageDialog(this,
                            "Chofer externo encontrado.\nAsignarle 5% de comisión e ingresar su ingreso bruto correspondiente.",
                            "Chofer externo", JOptionPane.INFORMATION_MESSAGE);
                }

                encontrado = true;
                break;
            }
        }

        if (!encontrado) {
            JOptionPane.showMessageDialog(this, "No se encontró ningún registro con ese nombre o placa.");
        }

     */

    private void txtBuscarPlacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarPlacaActionPerformed

    }//GEN-LAST:event_txtBuscarPlacaActionPerformed

    private void btnBorrarDatoTablaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarDatoTablaActionPerformed
        // TODO add your handling code here:

        int filaSeleccionada = jTableRegistroUnidad.getSelectedRow();
        if (filaSeleccionada >= 0) {
            javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) jTableRegistroUnidad.getModel();
            model.removeRow(filaSeleccionada);
            JOptionPane.showMessageDialog(this, "Fila eliminada correctamente.", "Eliminación", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "Selecciona una fila para eliminar.", "Advertencia", JOptionPane.WARNING_MESSAGE);
        }

        /*
        Una modificion que  rpuede tener es que    cuando presione borrar dato se borre tanto  aqui en la tabla y en la base de datos 
        podria  implementarse pero abria que ver si es nesesario ya que estaria modificando el usuario unico directamente la base de datos algo que
        capaz y no queremos
         */

    }//GEN-LAST:event_btnBorrarDatoTablaActionPerformed

    private void btnCargarDataBaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargarDataBaseActionPerformed
        // TODO add your handling code here:
        cargarDatosDesdeBaseDeDatos();
    }//GEN-LAST:event_btnCargarDataBaseActionPerformed

    private void cargarDatosDesdeBaseDeDatos() {
        UnidadDAO dao = new UnidadDAO();
        List<Object[]> unidades = dao.obtenerUnidades();

        DefaultTableModel model = (DefaultTableModel) jTableRegistroUnidad.getModel();
        model.setRowCount(0); // Limpiar tabla antes de cargar

        for (Object[] fila : unidades) {
            model.addRow(fila);
        }

        JOptionPane.showMessageDialog(this, "Datos cargados correctamente desde la base de datos.");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistroUnidadGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistroUnidadGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistroUnidadGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistroUnidadGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistroUnidadGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JpFondo;
    private javax.swing.JPanel JpGestionIngresos;
    private javax.swing.JPanel JpRegistroTurno;
    private javax.swing.JPanel JpReportes;
    private javax.swing.JComboBox<String> boxEstadoUnidad;
    private javax.swing.JComboBox<String> boxTipoUnidad;
    private javax.swing.JButton btnAdelante;
    private javax.swing.JButton btnBorrarDatoTabla;
    private javax.swing.JButton btnBuscarUnidad;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnCargarDataBase;
    private javax.swing.JButton btnLimpiarFormulario;
    private javax.swing.JButton btnRegistrarUnidad;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JTable jTableRegistroUnidad;
    private javax.swing.JTextField txtBuscarPlaca;
    private javax.swing.JTextField txtNombrePropietario;
    private javax.swing.JTextField txtNumComercial;
    private javax.swing.JTextField txtNumPlaca;
    private javax.swing.JTextField txtNumTelefono;
    // End of variables declaration//GEN-END:variables
}
